obj-$(CONFIG_PM_DEVFREQ)	+= devfreq.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_ONDEMAND)	+= governor_simpleondemand.o
obj-$(CONFIG_DEVFREQ_GOV_SIMPLE_USAGE)	+= governor_simpleusage.o
obj-$(CONFIG_DEVFREQ_GOV_PERFORMANCE)	+= governor_performance.o
obj-$(CONFIG_DEVFREQ_GOV_PM_QOS)	+= governor_pm_qos.o
obj-$(CONFIG_DEVFREQ_GOV_POWERSAVE)	+= governor_powersave.o
obj-$(CONFIG_DEVFREQ_GOV_USERSPACE)	+= governor_userspace.o

# DEVFREQ Drivers
obj-$(CONFIG_ARM_EXYNOS4_BUS_DEVFREQ)	+= exynos4_bus.o
obj-$(CONFIG_ARM_EXYNOS4270_BUS_DEVFREQ)	+= exynos4270_bus_mif.o exynos4270_bus_int.o
obj-$(CONFIG_ARM_EXYNOS4270_BUS_DEVFREQ)	+= exynos4270_ppmu.o
obj-$(CONFIG_ARM_EXYNOS5250_BUS_DEVFREQ)	+= exynos5250_bus_mif.o exynos5250_bus_int.o
obj-$(CONFIG_ARM_EXYNOS5250_BUS_DEVFREQ)	+= exynos5_ppmu.o
